<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWindowsForms>true</UseWindowsForms>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyVersion>2026.9.18.1101</AssemblyVersion>
    <FileVersion>2026.9.18.1101</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ArduinoAsDevice.Net\ArduinoAsDevice.Net.csproj" />
  </ItemGroup>

</Project>
