<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>7.3</LangVersion>
    <RootNamespace>ArduinoAsDevice</RootNamespace>
    <AssemblyName>ArduinoAsDevice</AssemblyName>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
  </PropertyGroup>

  <ItemGroup>
    <Compile Include="..\Shared\**\*.cs" LinkBase="Shared" />
  </ItemGroup>

</Project>
