<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>disable</Nullable>
    <AssemblyVersion>2026.9.18.0939</AssemblyVersion>
    <FileVersion>2026.9.18.0939</FileVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\ArduinoAsDevice.Net\ArduinoAsDevice.Net.csproj" />
  </ItemGroup>

</Project>
